// File generated by flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxKggIbNoyWErMiEkOMbOdekMjdoLDdPI',
    appId: '1:407287431542:android:cb94373c60ee4d66027a57',
    messagingSenderId: '407287431542',
    projectId: 'quote-gallery-fddfd',
    storageBucket: 'quote-gallery-fddfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1tqIEQbhln7Jn9ZYmZEsdK-seIbpeIQQ',
    appId: '1:407287431542:ios:ef4146d6151c7ee1027a57',
    messagingSenderId: '407287431542',
    projectId: 'quote-gallery-fddfd',
    storageBucket: 'quote-gallery-fddfd.firebasestorage.app',
    iosBundleId: 'com.example.quoteGallery',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxKggIbNoyWErMiEkOMbOdekMjdoLDdPI',
    appId: '1:407287431542:web:quote_gallery',
    messagingSenderId: '407287431542',
    projectId: 'quote-gallery-fddfd',
    authDomain: 'quote-gallery-fddfd.firebaseapp.com',
    storageBucket: 'quote-gallery-fddfd.firebasestorage.app',
    measurementId: "G-41CP5RKWK6",
  );
}
